name: GitHub Profile Summary Cards

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          THEME: default
