name: GitHub-Profile-Summary-Cards

on:
  schedule: # jalan otomatis tiap jam 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}   # pakai secret buatanmu
        with:
          USERNAME: ${{ github.repository_owner }}      # otomatis sesuai owner repo
